function CINEMATICABRUNO = importfile_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CINEMATICABRUNO = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  CINEMATICABRUNO = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CINEMATICABRUNO = importfile("D:\Documents\USP\Palestras_Aulas\programacao_computacional\minicurso\encontro4\2_Arquivos-CSV\CINEMATICA_BRUNO.csv", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2022 12:40:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 44);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "TakeName", "V03A_004", "TakeNotes", "VarName6", "CaptureFrameRate", "VarName8", "ExportFrameRate", "VarName10", "CaptureStartTime", "VarName12", "TotalFramesinTake", "VarName14", "TotalExportedFrames", "VarName16", "RotationType", "XZY", "LengthUnits", "Meters", "CoordinateSpace", "Global", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44"];
opts.SelectedVariableNames = ["TakeName", "V03A_004", "TakeNotes", "VarName6", "CaptureFrameRate", "VarName8", "ExportFrameRate", "VarName10", "CaptureStartTime", "VarName12", "TotalFramesinTake", "VarName14", "TotalExportedFrames", "VarName16", "RotationType", "XZY", "LengthUnits", "Meters", "CoordinateSpace", "Global", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44"];
opts.VariableTypes = ["char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [1, 2], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
CINEMATICABRUNO = readtable(filename, opts);

%% Convert to output type
CINEMATICABRUNO = table2array(CINEMATICABRUNO);
end