function CINEMATICABRUNO = importfile_text(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CINEMATICABRUNO = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  CINEMATICABRUNO = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CINEMATICABRUNO = importfile("D:\Documents\USP\Palestras_Aulas\programacao_computacional\minicurso\encontro4\2_Arquivos-CSV\CINEMATICA_BRUNO.csv", [2, 2]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2022 12:36:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 44);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "TakeName", "V03A_004", "TakeNotes", "VarName6", "CaptureFrameRate", "VarName8", "ExportFrameRate", "VarName10", "CaptureStartTime", "VarName12", "TotalFramesinTake", "VarName14", "TotalExportedFrames", "VarName16", "RotationType", "XZY", "LengthUnits", "Meters", "CoordinateSpace", "Global", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44"];
opts.SelectedVariableNames = ["TakeName", "V03A_004", "TakeNotes", "VarName6", "CaptureFrameRate", "VarName8", "ExportFrameRate", "VarName10", "CaptureStartTime", "VarName12", "TotalFramesinTake", "VarName14", "TotalExportedFrames", "VarName16", "RotationType", "XZY", "LengthUnits", "Meters", "CoordinateSpace", "Global", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44"];
opts.VariableTypes = ["char", "char", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
CINEMATICABRUNO = readtable(filename, opts);

%% Convert to output type
CINEMATICABRUNO = table2array(CINEMATICABRUNO);

CINEMATICABRUNO = CINEMATICABRUNO(1,:); 
end