function acelVert = importfile_vel(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACELVERT = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  ACELVERT = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  acelVert = importfile("D:\Documents\USP\Palestras_Aulas\programacao_computacional\minicurso\encontro4\2_Arquivos-CSV\acelVert.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2022 12:41:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Tempoms", "Trajetria1"];
opts.VariableTypes = ["double", "double"];
opts = setvaropts(opts, 2, "TrimNonNumeric", true);
opts = setvaropts(opts, 2, "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
acelVert = readtable(filename, opts);

%% Convert to output type
acelVert = table2array(acelVert);
end