function databaseimc = importfile_imctable(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DATABASEIMC = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DATABASEIMC = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DATABASEIMC = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  databaseimc = importfile("D:\Documents\USP\Palestras_Aulas\programacao_computacional\minicurso\encontro4\3_Arquivos-Excel\database_imc.xlsx", "Sheet1", [2, 101]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Feb-2022 12:51:08

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 101];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Nome", "ID_participante", "Idade", "Estaturacm", "Estaturam", "Massa"];
opts.SelectedVariableNames = ["Nome", "ID_participante", "Idade", "Estaturacm", "Estaturam", "Massa"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
databaseimc = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    databaseimc = [databaseimc; tb]; %#ok<AGROW>
end

end