function data1 = import_forceplate_data(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DATA1 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  DATA1 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  DATA1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  data1 = importfile("D:\Documents\USP\Palestras_Aulas\programacao_computacional\minicurso\github\aulas_programacao\encontro6\dados\salto\data1.xlsx", "Sheet1", [2, 10001]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Apr-2022 20:21:54

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 10001];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["time", "fx", "fy", "fz"];
opts.SelectedVariableNames = ["time", "fx", "fy", "fz"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
data1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    data1 = [data1; tb]; %#ok<AGROW>
end

%% Convert to output type
data1 = table2array(data1);
end